"""position exchange columns

Revision ID: a91d1ad81042
Revises: e05cdbeef361
Create Date: 2026-10-07 21:04:41.698030

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a91d1ad81042"
down_revision: str | Sequence[str] | None = "e05cdbeef361"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "active_positions", sa.Column("quantity", sa.Numeric(precision=30, scale=8), nullable=True)
    )
    op.add_column(
        "active_positions", sa.Column("exchange_ref", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("active_positions", "exchange_ref")
    op.drop_column("active_positions", "quantity")
    # ### end Alembic commands ###
